// E-commerce Products
export var products = [
  {
    id: "1",
    product_discount: "20",
    product_title: "Smart Watch",
    product_price: "25",
    product_image: "assets/media/images/Products/smart-watch.png",
    product_brand_name: "Premium",
    category: "Electronics",
    product_id: "SKU-345-356",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "2",
    product_discount: "25",
    product_title: "LRT Wireless Headphone",
    product_price: "10",
    product_image: "assets/media/images/Products/headphone1.png",
    product_brand_name: "LRT",
    category: "Electronics",
    product_id: "SKU-345-366",
    status: "Out of Stock",
    stock: "100",
  },
  {
    id: "3",
    product_title: "LRT Wired Headphone",
    product_discount: "50",
    product_price: "25",
    product_image: "assets/media/images/Products/headphone2.png",
    product_brand_name: "LRT",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "4",
    product_title: "Sigma Mobile SE (6, 128GB)",
    product_discount: "15",
    product_price: "100",
    product_brand_name: "Xenon X",
    product_image: "assets/media/images/Products/mobile4.png",
    category: "Electronics",
    product_id: "SKU-375-420",
    status: "In Stock",
    stock: "20",
  },
  {
    id: "5",
    product_title: "Ultra Basic Laptop i3",
    product_discount: "70",
    product_price: "100",
    product_image: "assets/media/images/Products/laptop.png",
    product_brand_name: "Ultra",
    category: "Electronics",
    product_id: "SKU-385-666",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "6",
    product_discount: "25",
    product_title: " Ila Wireless Mouse",
    product_price: "10",
    product_image: "assets/media/images/Products/mouse.png",
    product_brand_name: "Ila",
    category: "Electronics",
    product_id: "SKU-315-116",
    status: "In Stock",
    stock: "500",
  },
  {
    id: "7",
    product_title: "Lemon Wired Keyboard",
    product_discount: "20",
    product_price: "50",
    product_image: "assets/media/images/Products/keyboard.png",
    product_brand_name: "Lemon",
    category: "Electronics",
    product_id: "SKU-356-222",
    status: "In Stock",
    stock: "100",
  },
  {
    id: "8",
    product_discount: "20",
    product_title: "TRE Base Laptop",
    product_price: "100",
    product_image: "assets/media/images/Products/laptop2.png",
    product_brand_name: "TRE",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "Out of Stock",
    stock: "10",
  },
  {
    id: "9",
    product_title: "Stoke Desktop 16 S",
    product_discount: "20",
    product_price: "400",
    product_image: "assets/media/images/Products/desktop-1.png",
    product_brand_name: "Stoke",
    category: "Electronics",
    product_id: "SKU-345-444",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "10",
    product_discount: "25",
    product_title: "Blamer Slim Tablet",
    product_price: "650",
    product_image: "assets/media/images/Products/ipad2.png",
    product_brand_name: "Blamer",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "300",
  },
  {
    id: "11",
    product_title: "Sizo Mobile (4, 64GB)",
    product_discount: "50",
    product_price: "25",
    product_image: "assets/media/images/Products/mobile3.png",
    product_brand_name: "Sizo",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "400",
  },
  {
    id: "12",
    product_title: "TRE Laptop White i5",
    product_discount: "15",
    product_price: "30",
    product_brand_name: "Parker",
    product_image: "assets/media/images/Products/laptop3.png",
    category: "Electronics",
    product_id: "SKU-111-466",
    status: "In Stock",
    stock: "80",
  },
  {
    id: "13",
    product_title: "Sigma Mobile note 4",
    product_price: "100",
    product_discount: "70",
    product_image: "assets/media/images/Products/mobile2.png",
    product_brand_name: "Sigma",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "Out of Stock",
    stock: "100",
  },
  {
    id: "14",
    product_title: "Blamer  Tablet light",
    product_discount: "25",
    product_price: "10",
    product_brand_name: "Blamer",
    product_image: "assets/media/images/Products/ipad.png",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "15",
    product_title: "Stoke Desktop 13 S",
    product_price: "250",
    product_discount: "70",
    product_image: "assets/media/images/Products/desktop-2.png",
    product_brand_name: "Stoke",
    category: "Electrinics",
    product_id: "SKU-399-786",
    status: "In Stock",
    stock: "200",
  },
  {
    id: "16",
    product_title: "LRT Wired Headphone",
    product_discount: "15",
    product_price: "100",
    product_brand_name: "Daber",
    product_image: "assets/media/images/Products/headphone1.png",
    category: "Electrinics",
    product_id: "SKU-330-556",
    status: "In Stock",
    stock: "150",
  },
  {
    id: "17",
    product_title: "Ila Wireless Mouse",
    product_discount: "25",
    product_price: "39",
    product_brand_name: "Dairy Milk",
    product_image: "assets/media/images/Products/mouse.png",
    category: "Electrinics",
    product_id: "SKU-375-466",
    status: "Out of Stock",
    stock: "120",
  },
  {
    id: "18",
    product_discount: "20",
    product_title: "Smart Watch",
    product_price: "25",
    product_image: "assets/media/images/Products/smart-watch.png",
    product_brand_name: "Premium",
    category: "Electronics",
    product_id: "SKU-345-356",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "19",
    product_discount: "25",
    product_title: "Stoke laptop 13 S",
    product_price: "10",
    product_image: "assets/media/images/Products/laptop2.png",
    product_brand_name: "Stoke",
    category: "Electronics",
    product_id: "SKU-345-366",
    status: "Out of Stock",
    stock: "100",
  },
  {
    id: "20",
    product_title: "LRT Wired Headphone",
    product_discount: "50",
    product_price: "25",
    product_image: "assets/media/images/Products/mobile3.png",
    product_brand_name: "Sakti",
    category: "Electronics",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "50",
  },
];
export var orders = [
  {
    id: "1",
    product_title: "Soft Drink",
    product_price: "39",
    orderId: "SKU-345",
    customer_image: "assets/media/images/users/3.png",
    ship_date: "23 March 2021",
    customer_name: "Olivia Pots",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Second Floar, NY ",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "2",
    product_title: "Cashew",
    product_price: "25",
    orderId: "SKU-353",
    ship_date: "24 April 2021",
    customer_name: "Tim Pane",
    phone: "+21 (988) 234-4537",
    status: "Delivered",
    customer_address: "27/2 Block B, Behind Scalp, NY ",
    payment: "Recieved",
    customer_image: "assets/media/images/users/4.png",
  },
  {
    id: "3",
    product_title: "IceCreame",
    product_price: "10",
    customer_image: "assets/media/images/users/5.png",
    orderId: "SKU-745",
    ship_date: "23 March 2021",
    customer_name: "Eon Alfred",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Tejas Tower, SF ",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "4",
    product_title: "Fruits Milk Shake",
    product_price: "100",
    customer_image: "assets/media/images/users/6.png",
    orderId: "SKU-345",
    ship_date: "23 January 2021",
    customer_name: "Steve Butler",
    phone: "+21 (988) 234-4537",
    customer_address: "638F/D Block F, Rose Park , California ",
    status: "Canceled",
    payment: "Canceled",
  },
  {
    id: "5",
    product_title: "KIWI",
    product_price: "10",
    customer_image: "assets/media/images/users/6.png",
    orderId: "SKU-455",
    ship_date: "29 oct 2020",
    customer_name: "Barry Allen",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Second Floar, NY ",
    status: "Processing",
    payment: "Pending",
  },
  {
    id: "6",
    product_title: "Blaser Slimfit",
    product_price: "650",
    customer_image: "assets/media/images/users/7.png",
    orderId: "SKU-345",
    ship_date: "23 March 2021",
    customer_name: "Garry Castern",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Second Floar, NY ",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "7",
    product_title: "Women Top",
    product_price: "250",
    orderId: "SKU-353",
    ship_date: "24 April 2021",
    customer_image: "assets/media/images/users/8.png",
    customer_address: "27/2 Block B, Second Floar, NY ",
    customer_name: "Maxim Warner",
    phone: "+21 (988) 234-4537",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "8",
    product_title: "Dry fruits",
    product_price: "100",
    orderId: "SKU-745",
    ship_date: "23 March 2021",
    customer_name: "Markella Mawle",
    customer_image: "assets/media/images/users/9.png",
    customer_address: "27/2 Block B, Second Floar, NY ",
    phone: "+21 (988) 234-4537",
    status: "Delivered",
    payment: "Recieved",
  },
];
export var coupons = [
  {
    id: "1",
    coupon_name: "Summer Discount",
    coupon_code: "Summer21",
    created: "21 May, 2021",
    status: "Active",
    deadline: "23 June, 2021",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "2",
    coupon_name: "Winter Discount",
    coupon_code: "Winter20",
    created: "21 Nov, 2020",
    status: "Inactive",
    deadline: "21 December, 2020",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "3",
    coupon_name: "Ramadan",
    coupon_code: "Ramadan21",
    created: "21 April, 2021",
    status: "Active",
    deadline: "18 Sept, 2021",
    redeem: "8 Out of 10 Codes",
    percetage: "80",
  },
  {
    id: "4",
    coupon_name: "Eid Sale",
    coupon_code: "Eid21",
    created: "21 June, 2021",
    status: "Active",
    deadline: "03 October , 2021",
    redeem: "6 Out of 10 Codes",
    percetage: "60",
  },
  {
    id: "5",
    coupon_name: "Mansoon Offer",
    coupon_code: "Mansoon10",
    created: "21 June, 2021",
    status: "Active",
    deadline: "23 July, 2021",
    redeem: "0 out of 5 coupons",
    percetage: "0",
  },
  {
    id: "6",
    coupon_name: "Holi Sale",
    coupon_code: "HoliFestival",
    created: "01 March, 2021",
    status: "Inactive",
    deadline: "2 April, 2021",
    redeem: "8 out of 10 coupons",
    percetage: "80",
  },
  {
    id: "7",
    coupon_name: "Novratri Sale",
    coupon_code: "JMD9",
    created: "05 April, 2021",
    status: "Inactive",
    deadline: "18 May, 2021",
    redeem: "10 out of 15 coupons",
    percetage: "75",
  },
  {
    id: "8",
    coupon_name: "Covid Relief Sale",
    coupon_code: "CovidHelp19",
    created: "21 Jun, 2021",
    status: "Active",
    deadline: "03 October , 2021",
    redeem: "5 out of 10 coupons",
  },
  {
    id: "9",
    coupon_name: "Summer Discount",
    coupon_code: "Summer21",
    created: "21 May, 2021",
    status: "Active",
    deadline: "23 June, 2021",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "10",
    coupon_name: "Winter Discount",
    coupon_code: "Winter20",
    created: "21 Nov, 2020",
    status: "Inactive",
    deadline: "21 December, 2020",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "11",
    coupon_name: "Ramadan",
    coupon_code: "Ramadan21",
    created: "21 April, 2021",
    status: "Active",
    deadline: "18 Sept, 2021",
    redeem: "8 Out of 10 Codes",
    percetage: "80",
  },
  {
    id: "12",
    coupon_name: "Eid Sale",
    coupon_code: "Eid21",
    created: "21 June, 2021",
    status: "Active",
    deadline: "03 October , 2021",
    redeem: "6 Out of 10 Codes",
    percetage: "60",
  },
  {
    id: "13",
    coupon_name: "Mansoon Offer",
    coupon_code: "Mansoon10",
    created: "21 June, 2021",
    status: "Active",
    deadline: "23 July, 2021",
    redeem: "0 out of 5 coupons",
    percetage: "0",
  },
];
export var categories = [
  {
    id: "1",
    category_name: "Home Appliances",
    description: "AC, LED",
    type: "Electronics",
    image: "assets/media/images/Products/electronics.jpg",
  },
  {
    id: "1",
    category_name: "Mens Clothes",
    description: "Jeans,Shirt",
    type: "Clothe",
    image: "assets/media/images/Products/men-clothe.jpg",
  },
  {
    id: "1",
    category_name: "Women Accessories",
    description: "Earings, Bangles",
    type: "Fashiion",
    image: "assets/media/images/Products/Accesories.jpg",
  },

  {
    id: "2",
    category_name: "Fruits & Vegitables",
    description: "Oil, Beans",
    type: "Electronics",
    image: "assets/media/images/Products/Electronics.jpg",
  },
  {
    id: "3",
    category_name: "Shoes",
    description: "Sports Shoes, Formal Shoes",
    type: "Footwear",
    image: "assets/media/images/Products/footwear.jpg",
  },
  {
    id: "4",
    category_name: "Mobile Acceesories",
    description: "headphone, Speakers",
    type: "Electrinic",
    image: "assets/media/images/Products/mobile_accesories.png",
  },
  {
    id: "5",
    category_name: "Mobiles",
    description: "Mobile, Laptop",
    type: "Electronics",
    image: "assets/media/images/Products/electronics.jpg",
  },
  {
    id: "6",
    category_name: "Women Clothes",
    description: "Sari, Top",
    type: "Clothe",
    image: "assets/media/images/Products/women-clothe.jpg",
  },
];
export var customers = [
  {
    name: "Morgen Smith",
    star: "true",
    orders: "55",
    joined_date: "28 Dec 2018",
    rewards: "$68",
    image: "assets/media/images/users/10.png",
    phone: "+21 (988) 234-4537",
    email: "test@123gmail.com",
  },
  {
    name: " Elendil Sen",
    star: "false",
    joined_date: "14 April 2020",
    rewards: "$92",
    email: "test@123gmail.com",
    orders: "20",
    image: "assets/media/images/users/20.png",
    phone: "+21 (988) 504-2552",
  },
  {
    name: "Nyrie Stark",
    email: "test@123gmail.com",
    star: "false",
    orders: "106",
    joined_date: "30 Oct 2017",
    rewards: "$72",
    image: "assets/media/images/users/12.png",
    phone: "+21 (988) 454-3572",
  },
  {
    name: "Olivia Pots",
    email: "test@123gmail.com",
    joined_date: "25 Sept 2017",
    rewards: "$820",
    star: "true",
    orders: "70",
    image: "assets/media/images/users/13.png",
    phone: "+21 (988) 869-2568",
  },
  {
    name: "Emma Richerdson",
    star: "false",
    joined_date: "30 Nov 2020",
    rewards: "$72",
    email: "test@123gmail.com",
    orders: "40",
    image: "assets/media/images/users/14.png",
    phone: "+21 (988) 978-2559",
  },
  {
    name: "Monika Hamsworth",
    star: "false",
    email: "test@123gmail.com",
    orders: "10",
    joined_date: "18 Oct 2016",
    rewards: "$72",
    image: "assets/media/images/users/15.png",
    phone: "+21 (988) 234-4537",
  },
  {
    name: " Ketty Lang ",
    star: "false",
    email: "test@123gmail.com",
    orders: "20",
    joined_date: "30 Aug 2018",
    rewards: "$72",
    image: "assets/media/images/users/16.png",
    phone: "+21 (988) 504-2552",
  },
  {
    name: "Mathiny Stokes  ",
    star: "false",
    email: "test@123gmail.com",
    orders: "106",
    joined_date: "13 Aug 2019",
    rewards: "$68",
    image: "assets/media/images/users/17.png",
    phone: "+21 (988) 454-3572",
  },
  {
    name: "Maxim Warner",
    star: "true",
    joined_date: "30 Jun 2019",
    rewards: "$29",
    email: "test@123gmail.com",
    orders: "28",
    image: "assets/media/images/users/18.png",
    phone: "+21 (988) 869-2568",
  },
  {
    name: "Atly Gunn",
    star: "true",
    email: "test@123gmail.com",
    orders: "14",
    joined_date: "30 May 2018",
    rewards: "$72",
    image: "assets/media/images/users/15.png",
    phone: "+21 (988) 978-2559",
  },
  {
    name: "Netly Mullan",
    star: "true",
    joined_date: "30 Aug 2018",
    rewards: "$50",
    email: "test@123gmail.com",
    orders: "40",
    image: "assets/media/images/users/17.png",
    phone: "+21 (988) 978-2559",
  },
  {
    name: "Steave Warner",
    star: "true",
    email: "test@123gmail.com",
    orders: "55",
    joined_date: "30 Feb 2020",
    rewards: "$50",
    image: "assets/media/images/users/20.png",
    phone: "+21 (988) 234-4537",
  },
  {
    name: " Scott Lang ",
    star: "true",
    joined_date: "21 Feb 2015",
    rewards: "$257",
    email: "test@123gmail.com",
    orders: "20",
    image: "assets/media/images/users/18.png",
    phone: "+21 (988) 504-2552",
  },
  {
    name: "Robert Stark",
    star: "false",
    joined_date: "01 March 2012",
    rewards: "$446",
    email: "test@123gmail.com",
    orders: "106",
    image: "assets/media/images/users/18.png",
    phone: "+21 (988) 454-3572",
  },
  {
    name: "David Smith",
    joined_date: "21 July 2015",
    rewards: "$557",
    email: "test@123gmail.com",
    star: "true",
    orders: "70",
    image: "assets/media/images/users/19.png",
    phone: "+21 (988) 869-2568",
  },
  {
    name: "Kane Richerdson",
    star: "false",
    email: "test@123gmail.com",
    orders: "40",
    joined_date: "14 Dec 2018",
    rewards: "$68",
    image: "assets/media/images/users/18.png",
    phone: "+21 (988) 978-2559",
  },
];
