// E-commerce Products
export var products = [
  {
    id: "1",
    product_discount: "20",
    product_title: "Cashew",
    product_price: "25",
    product_image: "assets/media/images/Products/cashews.jpg",
    product_brand_name: "Premium",
    category: "Grocery",
    product_id: "SKU-345-356",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "2",
    product_discount: "25",
    product_title: "IceCreame",
    product_price: "10",
    product_image: "assets/media/images/Products/icecreme.jpg",
    product_brand_name: "Ring Bell",
    category: "Grocery",
    product_id: "SKU-345-366",
    status: "Out of Stock",
    stock: "100",
  },
  {
    id: "3",
    product_title: "Coconut",
    product_discount: "50",
    product_price: "25",
    product_image: "assets/media/images/Products/coconut.jpg",
    product_brand_name: "Sakti",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "4",
    product_title: "Mix Fruits",
    product_discount: "15",
    product_price: "100",
    product_brand_name: "Parker",
    product_image: "assets/media/images/Products/fruit-mix.jpg",
    category: "Grocery",
    product_id: "SKU-375-420",
    status: "In Stock",
    stock: "20",
  },
  {
    id: "5",
    product_title: "Creamy Cheese",
    product_discount: "70",
    product_price: "100",
    product_image: "assets/media/images/Products/cheese.jpg",
    product_brand_name: "Rischards",
    category: "Grocery",
    product_id: "SKU-385-666",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "6",
    product_discount: "25",
    product_title: "KIWI",
    product_price: "10",
    product_image: "assets/media/images/Products/Kiwi.jpg",
    product_brand_name: "Pixa",
    category: "Grocery",
    product_id: "SKU-315-116",
    status: "In Stock",
    stock: "500",
  },
  {
    id: "7",
    product_title: "Juice Lemon",
    product_discount: "20",
    product_price: "50",
    product_image: "assets/media/images/Products/lemon.jpg",
    product_brand_name: "Sakti",
    category: "Grocery",
    product_id: "SKU-356-222",
    status: "In Stock",
    stock: "100",
  },
  {
    id: "8",
    product_discount: "15",
    product_title: "Fruits Milk Shake",
    product_price: "100",
    product_image: "assets/media/images/Products/fuitshake.jpg",
    product_brand_name: "Daber",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "Out of Stock",
    stock: "10",
  },
  {
    id: "9",
    product_title: "Fruit  Juice",
    product_discount: "20",
    product_price: "400",
    product_image: "assets/media/images/Products/fruit-juice.jpg",
    product_brand_name: "Premium",
    category: "Grocery",
    product_id: "SKU-345-444",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "10",
    product_discount: "25",
    product_title: "Blaser Slimfit",
    product_price: "650",
    product_image: "assets/media/images/Products/Blazer.jpg",
    product_brand_name: "Peter England",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "300",
  },
  {
    id: "11",
    product_title: "Cauliflower",
    product_discount: "50",
    product_price: "25",
    product_image: "assets/media/images/Products/caulifflower.jpg",
    product_brand_name: "Sakti",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "400",
  },
  {
    id: "12",
    product_title: "Coriander Fresh Leafs",
    product_discount: "15",
    product_price: "30",
    product_brand_name: "Parker",
    product_image: "assets/media/images/Products/coriander.jpg",
    category: "Grocery",
    product_id: "SKU-111-466",
    status: "In Stock",
    stock: "80",
  },
  {
    id: "13",
    product_title: "Dry fruits",
    product_price: "100",
    product_discount: "70",
    product_image: "assets/media/images/Products/dry-fruit.jpg",
    product_brand_name: "Rischards",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "Out of Stock",
    stock: "100",
  },
  {
    id: "14",
    product_title: "Pasta",
    product_discount: "25",
    product_price: "10",
    product_brand_name: "Pixa",
    product_image: "assets/media/images/Products/pasta.jpg",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "15",
    product_title: "Women Top",
    product_price: "250",
    product_discount: "70",
    product_image: "assets/media/images/Products/w-top.jpg",
    product_brand_name: "Max",
    category: "Clothe",
    product_id: "SKU-399-786",
    status: "In Stock",
    stock: "200",
  },
  {
    id: "16",
    product_title: "Shampoo",
    product_discount: "15",
    product_price: "100",
    product_brand_name: "Daber",
    product_image: "assets/media/images/Products/shampoo.jpg",
    category: "Fashion",
    product_id: "SKU-330-556",
    status: "In Stock",
    stock: "150",
  },
  {
    id: "17",
    product_title: "Soft Drink",
    product_discount: "25",
    product_price: "39",
    product_brand_name: "Dairy Milk",
    product_image: "assets/media/images/Products/sofft-drink.jpg",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "Out of Stock",
    stock: "120",
  },
  {
    id: "18",
    product_discount: "20",
    product_title: "Cashew",
    product_price: "25",
    product_image: "assets/media/images/Products/cashews.jpg",
    product_brand_name: "Premium",
    category: "Grocery",
    product_id: "SKU-345-356",
    status: "In Stock",
    stock: "50",
  },
  {
    id: "19",
    product_discount: "25",
    product_title: "IceCreame",
    product_price: "10",
    product_image: "assets/media/images/Products/icecreme.jpg",
    product_brand_name: "Ring Bell",
    category: "Grocery",
    product_id: "SKU-345-366",
    status: "Out of Stock",
    stock: "100",
  },
  {
    id: "20",
    product_title: "Coconut",
    product_discount: "50",
    product_price: "25",
    product_image: "assets/media/images/Products/coconut.jpg",
    product_brand_name: "Sakti",
    category: "Grocery",
    product_id: "SKU-375-466",
    status: "In Stock",
    stock: "50",
  },
];
export var orders = [
  {
    id: "1",
    product_title: "Soft Drink",
    product_price: "39",
    orderId: "SKU-345",
    customer_image: "assets/media/images/users/300_3.jpg",
    ship_date: "23 March 2021",
    customer_name: "Sam Wilson",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Second Floar, NY ",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "2",
    product_title: "Cashew",
    product_price: "25",
    orderId: "SKU-353",
    ship_date: "24 April 2021",
    customer_name: "Tim Pane",
    phone: "+21 (988) 234-4537",
    status: "Delivered",
    customer_address: "27/2 Block B, Behind Scalp, NY ",
    payment: "Recieved",
    customer_image: "assets/media/images/users/300_4.jpg",
  },
  {
    id: "3",
    product_title: "IceCreame",
    product_price: "10",
    customer_image: "assets/media/images/users/300_5.jpg",
    orderId: "SKU-745",
    ship_date: "23 March 2021",
    customer_name: "Eon Alfred",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Tejas Tower, SF ",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "4",
    product_title: "Fruits Milk Shake",
    product_price: "100",
    customer_image: "assets/media/images/users/300_6.jpg",
    orderId: "SKU-345",
    ship_date: "23 January 2021",
    customer_name: "Steve Butler",
    phone: "+21 (988) 234-4537",
    customer_address: "638F/D Block F, Rose Park , California ",
    status: "Canceled",
    payment: "Canceled",
  },
  {
    id: "5",
    product_title: "KIWI",
    product_price: "10",
    customer_image: "assets/media/images/users/300_6.jpg",
    orderId: "SKU-455",
    ship_date: "29 oct 2020",
    customer_name: "Barry Allen",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Second Floar, NY ",
    status: "Processing",
    payment: "Pending",
  },
  {
    id: "6",
    product_title: "Blaser Slimfit",
    product_price: "650",
    customer_image: "assets/media/images/users/300_7.jpg",
    orderId: "SKU-345",
    ship_date: "23 March 2021",
    customer_name: "Garry Castern",
    phone: "+21 (988) 234-4537",
    customer_address: "27/2 Block B, Second Floar, NY ",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "7",
    product_title: "Women Top",
    product_price: "250",
    orderId: "SKU-353",
    ship_date: "24 April 2021",
    customer_image: "assets/media/images/users/300_8.jpg",
    customer_address: "27/2 Block B, Second Floar, NY ",
    customer_name: "Indi Warner",
    phone: "+21 (988) 234-4537",
    status: "Delivered",
    payment: "Recieved",
  },
  {
    id: "8",
    product_title: "Dry fruits",
    product_price: "100",
    orderId: "SKU-745",
    ship_date: "23 March 2021",
    customer_name: "Raj Mukherji",
    customer_image: "assets/media/images/users/300_9.jpg",
    customer_address: "27/2 Block B, Second Floar, NY ",
    phone: "+21 (988) 234-4537",
    status: "Delivered",
    payment: "Recieved",
  },
];
export var coupons = [
  {
    id: "1",
    coupon_name: "Summer Discount",
    coupon_code: "Summer21",
    created: "21 May, 2021",
    status: "Active",
    deadline: "23 June, 2021",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "2",
    coupon_name: "Winter Discount",
    coupon_code: "Winter20",
    created: "21 Nov, 2020",
    status: "Inactive",
    deadline: "21 December, 2020",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "3",
    coupon_name: "Ramadan",
    coupon_code: "Ramadan21",
    created: "21 April, 2021",
    status: "Active",
    deadline: "18 Sept, 2021",
    redeem: "8 Out of 10 Codes",
    percetage: "80",
  },
  {
    id: "4",
    coupon_name: "Eid Sale",
    coupon_code: "Eid21",
    created: "21 June, 2021",
    status: "Active",
    deadline: "03 October , 2021",
    redeem: "6 Out of 10 Codes",
    percetage: "60",
  },
  {
    id: "5",
    coupon_name: "Mansoon Offer",
    coupon_code: "Mansoon10",
    created: "21 June, 2021",
    status: "Active",
    deadline: "23 July, 2021",
    redeem: "0 out of 5 coupons",
    percetage: "0",
  },
  {
    id: "6",
    coupon_name: "Holi Sale",
    coupon_code: "HoliFestival",
    created: "01 March, 2021",
    status: "Inactive",
    deadline: "2 April, 2021",
    redeem: "8 out of 10 coupons",
    percetage: "80",
  },
  {
    id: "7",
    coupon_name: "Novratri Sale",
    coupon_code: "JMD9",
    created: "05 April, 2021",
    status: "Inactive",
    deadline: "18 May, 2021",
    redeem: "10 out of 15 coupons",
    percetage: "75",
  },
  {
    id: "8",
    coupon_name: "Covid Relief Sale",
    coupon_code: "CovidHelp19",
    created: "21 Jun, 2021",
    status: "Active",
    deadline: "03 October , 2021",
    redeem: "5 out of 10 coupons",
  },
  {
    id: "9",
    coupon_name: "Summer Discount",
    coupon_code: "Summer21",
    created: "21 May, 2021",
    status: "Active",
    deadline: "23 June, 2021",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "10",
    coupon_name: "Winter Discount",
    coupon_code: "Winter20",
    created: "21 Nov, 2020",
    status: "Inactive",
    deadline: "21 December, 2020",
    redeem: "5 Out of 10 Codes",
    percetage: "50",
  },
  {
    id: "11",
    coupon_name: "Ramadan",
    coupon_code: "Ramadan21",
    created: "21 April, 2021",
    status: "Active",
    deadline: "18 Sept, 2021",
    redeem: "8 Out of 10 Codes",
    percetage: "80",
  },
  {
    id: "12",
    coupon_name: "Eid Sale",
    coupon_code: "Eid21",
    created: "21 June, 2021",
    status: "Active",
    deadline: "03 October , 2021",
    redeem: "6 Out of 10 Codes",
    percetage: "60",
  },
  {
    id: "13",
    coupon_name: "Mansoon Offer",
    coupon_code: "Mansoon10",
    created: "21 June, 2021",
    status: "Active",
    deadline: "23 July, 2021",
    redeem: "0 out of 5 coupons",
    percetage: "0",
  },
];
export var categories = [
  {
    id: "1",
    category_name: "Home Appliances",
    description: "AC, LED",
    type: "Electronics",
    image: "assets/media/images/Products/electronics.jpg",
  },
  {
    id: "1",
    category_name: "Mens Clothes",
    description: "Jeans,Shirt",
    type: "Clothe",
    image: "assets/media/images/Products/men-clothe.jpg",
  },
  {
    id: "1",
    category_name: "Women Accessories",
    description: "Earings, Bangles",
    type: "Fashiion",
    image: "assets/media/images/Products/Accesories.jpg",
  },

  {
    id: "2",
    category_name: "Fruits & Vegitables",
    description: "Oil, Beans",
    type: "Grocery",
    image: "assets/media/images/Products/grocery.jpg",
  },
  {
    id: "3",
    category_name: "Shoes",
    description: "Sports Shoes, Formal Shoes",
    type: "Footwear",
    image: "assets/media/images/Products/footwear.jpg",
  },
  {
    id: "4",
    category_name: "Mobile Acceesories",
    description: "headphone, Speakers",
    type: "Electrinic",
    image: "assets/media/images/Products/mobile_accesories.png",
  },
  {
    id: "5",
    category_name: "Mobiles",
    description: "Mobile, Laptop",
    type: "Electronics",
    image: "assets/media/images/Products/electronics.jpg",
  },
  {
    id: "6",
    category_name: "Women Clothes",
    description: "Sari, Top",
    type: "Clothe",
    image: "assets/media/images/Products/women-clothe.jpg",
  },
];
export var customers = [
  {
    name: "Morgen Smith",
    star: "true",
    orders: "55",
    joined_date: "28 Dec 2018",
    rewards: "$68",
    image: "assets/media/images/users/300_10.jpg",
    phone: "+21 (988) 234-4537",
    email: "test@123gmail.com",
  },
  {
    name: " Mariya Sen",
    star: "false",
    joined_date: "14 April 2020",
    rewards: "$92",
    email: "test@123gmail.com",
    orders: "20",
    image: "assets/media/images/users/300_11.jpg",
    phone: "+21 (988) 504-2552",
  },
  {
    name: "Robert Stark",
    email: "test@123gmail.com",
    star: "false",
    orders: "106",
    joined_date: "30 Oct 2017",
    rewards: "$72",
    image: "assets/media/images/users/300_12.jpg",
    phone: "+21 (988) 454-3572",
  },
  {
    name: "David Smith",
    email: "test@123gmail.com",
    joined_date: "25 Sept 2017",
    rewards: "$820",
    star: "true",
    orders: "70",
    image: "assets/media/images/users/300_13.jpg",
    phone: "+21 (988) 869-2568",
  },
  {
    name: "Kane Richerdson",
    star: "false",
    joined_date: "30 Nov 2020",
    rewards: "$72",
    email: "test@123gmail.com",
    orders: "40",
    image: "assets/media/images/users/300_14.jpg",
    phone: "+21 (988) 978-2559",
  },
  {
    name: "Jhye Anderson",
    star: "false",
    email: "test@123gmail.com",
    orders: "10",
    joined_date: "18 Oct 2016",
    rewards: "$72",
    image: "assets/media/images/users/300_15.jpg",
    phone: "+21 (988) 234-4537",
  },
  {
    name: " Ketty Lang ",
    star: "false",
    email: "test@123gmail.com",
    orders: "20",
    joined_date: "30 Aug 2018",
    rewards: "$72",
    image: "assets/media/images/users/300_16.jpg",
    phone: "+21 (988) 504-2552",
  },
  {
    name: "Mathiny Stokes  ",
    star: "false",
    email: "test@123gmail.com",
    orders: "106",
    joined_date: "13 Aug 2019",
    rewards: "$68",
    image: "assets/media/images/users/300_17.jpg",
    phone: "+21 (988) 454-3572",
  },
  {
    name: "Simayra Finch",
    star: "true",
    joined_date: "30 Jun 2019",
    rewards: "$29",
    email: "test@123gmail.com",
    orders: "28",
    image: "assets/media/images/users/300_18.jpg",
    phone: "+21 (988) 869-2568",
  },
  {
    name: "Atly Gunn",
    star: "true",
    email: "test@123gmail.com",
    orders: "14",
    joined_date: "30 May 2018",
    rewards: "$72",
    image: "assets/media/images/users/300_19.jpg",
    phone: "+21 (988) 978-2559",
  },
  {
    name: "Kiyara Richerdson",
    star: "true",
    joined_date: "30 Aug 2018",
    rewards: "$50",
    email: "test@123gmail.com",
    orders: "40",
    image: "assets/media/images/users/300_20.jpg",
    phone: "+21 (988) 978-2559",
  },
  {
    name: "Steave Warner",
    star: "true",
    email: "test@123gmail.com",
    orders: "55",
    joined_date: "30 Feb 2020",
    rewards: "$50",
    image: "assets/media/images/users/300_21.jpg",
    phone: "+21 (988) 234-4537",
  },
  {
    name: " Scott Lang ",
    star: "true",
    joined_date: "21 Feb 2015",
    rewards: "$257",
    email: "test@123gmail.com",
    orders: "20",
    image: "assets/media/images/users/300_22.jpg",
    phone: "+21 (988) 504-2552",
  },
  {
    name: "Robert Stark",
    star: "false",
    joined_date: "01 March 2012",
    rewards: "$446",
    email: "test@123gmail.com",
    orders: "106",
    image: "assets/media/images/users/300_23.jpg",
    phone: "+21 (988) 454-3572",
  },
  {
    name: "David Smith",
    joined_date: "21 July 2015",
    rewards: "$557",
    email: "test@123gmail.com",
    star: "true",
    orders: "70",
    image: "assets/media/images/users/300_24.jpg",
    phone: "+21 (988) 869-2568",
  },
  {
    name: "Kane Richerdson",
    star: "false",
    email: "test@123gmail.com",
    orders: "40",
    joined_date: "14 Dec 2018",
    rewards: "$68",
    image: "assets/media/images/users/300_25.jpg",
    phone: "+21 (988) 978-2559",
  },
];
