export var holds = [
  {
    title: "Fix issue #43",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    imgHeader: "assets/media/images/cards/7.jpg",
    user_img: "assets/media/images/users/1.png",

    message: "02",
    file: "03",
  },
  {
    title: "Project DeadLine",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    user_img: "assets/media/images/users/2.png",
    message: "04",
    file: "01",
  },
  {
    title: "Add this to dashboard",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    imgHeader: "assets/media/images/cards/4.jpg",
    user_img: "assets/media/images/users/3.png",

    message: "02",
    file: "03",
  },
  {
    title: "InitelSap Project",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    imgHeader: "assets/media/images/cards/6.jpg",
    user_img: "assets/media/images/users/4.png",
    message: "04",
    file: "08",
  },
  {
    title: "Exam Project",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    user_img: "assets/media/images/users/9.png",
    message: "04",
    file: "03",
  },
  {
    title: "Fix issue #45",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    imgHeader: "assets/media/images/cards/7.jpg",
    user_img: "assets/media/images/users/1.png",

    message: "02",
    file: "03",
  },
  {
    title: "Fix Layout issue #15",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    user_img: "assets/media/images/users/2.png",
    message: "04",
    file: "01",
  },
  {
    title: "Fix Header issue #35",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    imgHeader: "assets/media/images/cards/7.jpg",
    user_img: "assets/media/images/users/3.png",

    message: "02",
    file: "03",
  },
  {
    title: "DB Crashed issue #40",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    imgHeader: "assets/media/images/cards/4.jpg",
    user_img: "assets/media/images/users/4.png",
    message: "04",
    file: "08",
  },
  {
    title: "Api Issue #67",
    content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
    user_img: "assets/media/images/users/9.png",
    message: "04",
    file: "03",
  },
];
// export var progresing = [
//   {
//     title: "Zydus Delivery Project ",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/1.jpg",
//     user_img: "assets/media/images/users/5.png",
//     notification: "May, 03",
//     message: "02",
//     file: "03",
//   },
//   {
//     title: "Project in Working",
//     user_img: "assets/media/images/users/5.png",
//     message: "02",
//     file: "03",
//   },
//   {
//     title: "InitelSap Project",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/6.jpg",
//     user_img: "assets/media/images/users/4.png",
//     message: "04",
//     file: "08",
//   },
//   {
//     title: "Exam Project",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/9.png",
//     message: "04",
//     file: "03",
//   },
//   {
//     title: "Fix issue #45",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/7.jpg",
//     user_img: "assets/media/images/users/1.png",

//     message: "02",
//     file: "03",
//   },
//   {
//     title: "Fix Layout issue #15",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/2.png",
//     message: "04",
//     file: "01",
//   },

//   {
//     title: "Api Issue #67",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/9.png",
//     message: "04",
//     file: "03",
//   },
// ];
// export var testing = [
//   {
//     title: "Exam Project",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/9.png",
//     message: "04",
//     file: "03",
//   },
//   {
//     title: "Fix issue #45",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/7.jpg",
//     user_img: "assets/media/images/users/1.png",

//     message: "02",
//     file: "03",
//   },
//   {
//     title: "Fix Layout issue #15",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/2.png",
//     message: "04",
//     file: "01",
//   },
//   {
//     title: "Fix Header issue #35",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/7.jpg",
//     user_img: "assets/media/images/users/3.png",

//     message: "02",
//     file: "03",
//   },
//   {
//     title: "DB Crashed issue #40",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/4.jpg",
//     user_img: "assets/media/images/users/4.png",
//     message: "04",
//     file: "08",
//   },
//   {
//     title: "Foody App",
//     imgHeader: "assets/media/images/cards/1.jpg",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/7.png",
//     user_img2: "assets/media/images/users/5.png",
//     notification: "May, 03",
//     message: "02",
//     file: "03",
//   },
//   {
//     title: "Api Issue #67",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/9.png",
//     message: "04",
//     file: "03",
//   },
// ];
// export var completed = [
//   {
//     title: "Rental",
//     imgHeader: "assets/media/images/cards/1.jpg",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/5.png",
//     notification: "May, 03",
//     message: "02",
//     file: "03",
//   },
//   {
//     title: "Fix issue #45",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/7.jpg",
//     user_img: "assets/media/images/users/1.png",
//     message: "02",
//     file: "03",
//   },
//   {
//     title: "DB Crashed issue #40",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     imgHeader: "assets/media/images/cards/4.jpg",
//     user_img: "assets/media/images/users/4.png",
//     message: "04",
//     file: "08",
//   },
//   {
//     title: "Api Issue #67",
//     content: "Phasellus ac augue vitae ligula sollicitudin feugiat",
//     user_img: "assets/media/images/users/9.png",
//     message: "04",
//     file: "03",
//   },
// ];
