//Invoices
export var invoices = [
  {
    id: "101",
    bill_from: "Redapple Inc.",
    bill_to: "Redit Inc",
    total_cost: "99",
    status: "Pending",
  },
  {
    id: "102",
    bill_from: "GreenApple Inc.",
    bill_to: "eService Inc",
    total_cost: "99",
    status: "Deleiverd",
  },
  {
    id: "103",
    bill_from: "RFc Inc.",
    bill_to: "ME Inc",
    total_cost: "99",
    status: "Shipped",
  },
  {
    id: "104",
    bill_from: "LitSharp Inc.",
    bill_to: "ByleCode Inc",
    total_cost: "99",
    status: "Deleiverd",
  },
  {
    id: "105",
    bill_from: "Oranges Inc.",
    bill_to: "eJob Inc",
    total_cost: "99",
    status: "Shipped",
  },
  {
    id: "105",
    bill_from: "Code Inc.",
    bill_to: "Shipra Inc",
    total_cost: "99",
    status: "Pending",
  },
];
//Conatct
export var contacts = [
  {
    name: "Morgen Smith",
    star: "true",
    occupation: "Php Developer",
    image: "assets/media/images/users/300_10.jpg",
    phone: "+21 (988) 234-4537",
    ratting: [1, 3, 3],
    email: "user@123.gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: " Mariya Sen",
    star: "false",
    occupation: "React Developer",
    image: "assets/media/images/users/300_11.jpg",
    phone: "+21 (988) 504-2552",
    ratting: [1, 5, 3],
    email: "user@123.gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Robert Stark",
    star: "false",
    occupation: "Angular Developer",
    image: "assets/media/images/users/300_12.jpg",
    phone: "+21 (988) 454-3572",
    ratting: [1, 3, 3],
    email: "user@452gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "David Smith",

    star: "true",
    occupation: "Graphic Designer",
    image: "assets/media/images/users/300_13.jpg",
    phone: "+21 (988) 869-2568",
    ratting: [1, 2, 3],
    email: "user@123.gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Kane Richerdson",
    star: "false",
    occupation: "Web Designer",
    image: "assets/media/images/users/300_14.jpg",
    phone: "+21 (988) 978-2559",
    ratting: [1, 2, 3],
    email: "user@123.reddit.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Jhye Anderson",
    star: "false",
    occupation: "Vue Developer",
    image: "assets/media/images/users/300_15.jpg",
    phone: "+21 (988) 234-4537",
    ratting: [1, 2, 3],
    email: "user@123.gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: " Ketty Lang ",
    star: "false",
    occupation: "React Developer",
    image: "assets/media/images/users/300_16.jpg",
    phone: "+21 (988) 504-2552",
    ratting: [1, 2, 3],
    email: "user@123.gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Mathiny Stokes  ",
    star: "false",
    occupation: "Angular Developer",
    image: "assets/media/images/users/300_17.jpg",
    phone: "+21 (988) 454-3572",
    ratting: [1, 2, 3],
    email: "user@12.hotmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Simayra Finch",
    star: "true",
    occupation: "Graphic Designer",
    image: "assets/media/images/users/300_18.jpg",
    phone: "+21 (988) 869-2568",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Atly Gunn",
    star: "true",
    occupation: "Web Designer",
    image: "assets/media/images/users/300_19.jpg",
    phone: "+21 (988) 978-2559",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Kiyara Richerdson",
    star: "true",
    occupation: "Web Designer",
    image: "assets/media/images/users/300_20.jpg",
    phone: "+21 (988) 978-2559",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Steave Warner",
    star: "true",
    occupation: "Php Developer",
    image: "assets/media/images/users/300_21.jpg",
    phone: "+21 (988) 234-4537",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: " Scott Lang ",
    star: "true",
    occupation: "React Developer",
    image: "assets/media/images/users/300_22.jpg",
    phone: "+21 (988) 504-2552",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Robert Stark",
    star: "false",
    occupation: "Angular Developer",
    image: "assets/media/images/users/300_23.jpg",
    phone: "+21 (988) 454-3572",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "David Smith",

    star: "true",
    occupation: "Graphic Designer",
    image: "assets/media/images/users/300_24.jpg",
    phone: "+21 (988) 869-2568",
    ratting: [1, 2, 3],
    email: "user@gmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    name: "Kane Richerdson",
    star: "false",
    occupation: "Web Designer",
    image: "assets/media/images/users/300_25.jpg",
    phone: "+21 (988) 978-2559",
    ratting: [1, 2, 3],
    email: "user@125hotmail.com",
    bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
];
//Tasks For Task Manager
export var tasks = [
  {
    id: "1",
    task_name: "Create the home page on the Promo Project",
    status: "In Progress",
    deadline: "23 June, 2021",
    completion: "35",
  },
  {
    id: "2",
    task_name: "Add  error pages - 404, 301, 500",
    status: "Completed",
    deadline: "21 December, 2020",
    completion: "100",
  },
  {
    id: "3",
    task_name: "Remove all catche for build Production",
    status: "Completed",
    deadline: "18 Sept, 2021",
    completion: "100",
  },
  {
    id: "4",
    task_name: "Fix sticky Header Issue in Seazep Project",
    status: "In Progress",
    deadline: "03 October , 2021",
    completion: "77",
  },
  {
    id: "5",
    task_name: "Create the landing page on the account module",
    status: "In Progress",
    deadline: "23 June, 2021",
    completion: "35",
  },
  {
    id: "6",
    task_name: "Redesign the chat interface",
    status: "Canceled",
    deadline: "21 March, 2020",
    completion: "0",
  },
  {
    id: "7",
    task_name: "Clear  production build issues",
    status: "Canceled",
    deadline: "18 Sept, 2021",
    completion: "0",
  },
  {
    id: "8",
    task_name: "Add permission in LTS version 2.1",
    status: "In Progress",
    deadline: "03 October , 2021",
    completion: "77",
  },
];
//for Notes
export var notes = [
  {
    id: "1",
    note_title: "This is new note",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "20 Oct 2021",
    note_author: "assets/media/images/users/user1.jpg",
    note_share_count: 5,
    note_author_name: "Indi",
  },
  {
    id: "2",
    note_title: "This is Second note",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "10 Aug 2021",
    note_author: "assets/media/images/users/user3.jpg",
    note_share_count: 2,
    note_author_name: "Caron",
  },
  {
    id: "3",
    note_title: "This is third note",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "15 May 2021",
    note_author: "assets/media/images/users/user5.jpg",
    note_share_count: 6,
    note_author_name: "Morgon",
  },
  {
    id: "4",
    note_title: "Change home page layout ",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "10 July 2021",
    note_author: "assets/media/images/users/user1.jpg",
    note_share_count: 5,
    note_author_name: "Caron",
  },
  {
    id: "5",
    note_title: "Make a dark theme",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "15 May 2021",
    note_author: "assets/media/images/users/user1.jpg",
    note_share_count: 2,
    note_author_name: "Morgon",
  },
  {
    id: "6",
    note_title: "Change the globle color ",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "10 July 2021",
    note_author: "assets/media/images/users/user3.jpg",
    note_share_count: 5,
    note_author_name: "Morgon",
  },
  {
    id: "7",
    note_title: "This is new note",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "20 Oct 2021",
    note_author: "assets/media/images/users/user1.jpg",
    note_share_count: 10,
    note_author_name: "Indi",
  },
  {
    id: "8",
    note_title: "This is Second note",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "10 Aug 2021",
    note_author: "assets/media/images/users/user3.jpg",
    note_share_count: 9,
    note_author_name: "Morgon",
  },
  {
    id: "9",
    note_title: "This is third note",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "15 May 2021",
    note_author: "assets/media/images/users/user5.jpg",
    note_author_name: "Indi",
    note_share_count: 6,
  },
  {
    id: "10",
    note_title: "Change home page layout ",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "10 July 2021",
    note_author: "assets/media/images/users/user1.jpg",
    note_share_count: 5,
    note_author_name: "Morgon",
  },
  {
    id: "11",
    note_title: "Make a dark theme",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "15 May 2021",
    note_author: "assets/media/images/users/user1.jpg",
    note_share_count: 1,
    note_author_name: "Seren",
  },
  {
    id: "12",
    note_title: "Change the globle color ",
    note_description:
      "Lorem ipsum dolor sit amet conse adipis belit. Expedita, optio non ipsam qui adipisci hic?",
    note_createdAt: "10 July 2021",
    note_author: "assets/media/images/users/user3.jpg",
    note_share_count: 8,
    note_author_name: "Seren",
  },
];
//Tickets
export var tickets = [
  {
    id: "1",
    ticket_title: "Fix issue of keyboard",
    ticket_desc: "This issue is occurinng since two days.",
    assign: "Tom",
    status: "Closed",
  },
  {
    id: "2",
    ticket_title: "Project Analysis and Review",
    ticket_desc: "The program evaluation and analyze the tasks .",
    assign: "Kane",
    status: "In Progress",
  },
  {
    id: "3",
    ticket_title: "Project on human happiness",
    ticket_desc: "Happiness is partly genetically based.",
    assign: "Morgon",
    status: "Pending",
  },
  {
    id: "4",
    ticket_title: "Project Analysis and Review",
    ticket_desc: "The program evaluation and analyze the tasks .",
    assign: "David",
    status: "In Progress",
  },
  {
    id: "5",
    ticket_title: "Fix issue of mouse",
    ticket_desc: "This issue is occurinng since two days",
    assign: "Indi",
    status: "Closed",
  },
  {
    id: "6",
    ticket_title: "Project Analysis and Review",
    ticket_desc: "The program evaluation and analyze the tasks .",
    assign: "Steave",
    status: "Closed",
  },
];
